# Generated by Django 4.1.10 on 2023-08-10 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0003_image_delete_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='media/images/'),
        ),
    ]
