# Generated by Django 4.1.10 on 2023-08-10 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0004_alter_image_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
