# Generated by Django 4.1.10 on 2023-08-10 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0005_alter_image_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='videos/')),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
