# Generated by Django 4.1.10 on 2023-08-10 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0007_subtitles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subtitles',
        ),
    ]
