# Generated by Django 4.1.10 on 2023-08-10 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0012_subtitle'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtitle',
            old_name='subtitle_text',
            new_name='text',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='video',
            new_name='video_file',
        ),
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
