# Generated by Django 4.1.10 on 2023-08-10 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0013_rename_subtitle_text_subtitle_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='title',
        ),
    ]
