# Generated by Django 4.1.10 on 2023-08-10 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0014_remove_video_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='title',
            field=models.CharField(default='sample', max_length=100),
        ),
    ]
