# Generated by Django 4.1.10 on 2023-08-10 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0015_video_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='title',
        ),
    ]
