# Generated by Django 4.1.10 on 2023-08-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0017_rename_text_subtitle_subtitle_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtitle',
            old_name='subtitle_text',
            new_name='text',
        ),
        migrations.AlterField(
            model_name='subtitle',
            name='timestamp',
            field=models.IntegerField(),
        ),
    ]
