# Generated by Django 4.1.10 on 2023-08-10 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0018_rename_subtitle_text_subtitle_text_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='video',
            new_name='video_file',
        ),
        migrations.AlterField(
            model_name='subtitle',
            name='timestamp',
            field=models.FloatField(),
        ),
    ]
