# Generated by Django 4.1.10 on 2023-08-10 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('function', '0019_rename_video_video_video_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subtitle',
            old_name='text',
            new_name='subtitle_text',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='video_file',
            new_name='video',
        ),
    ]
